import 'package:skyhighapp/entities/for_sky_api/order_data.dart';

class OrderDataModel extends OrderData {
  OrderDataModel(
      {required super.orderId,
      required super.profit,
      required super.city,
      required super.customerName,
      required super.productName,
      required super.rowId,
      required super.country,
      required super.discount,
      required super.customerId,
      required super.region,
      required super.quantity,
      required super.segment,
      required super.state,
      required super.shipMode,
      required super.subCategory,
      required super.postalCode,
      required super.shipDate,
      required super.category,
      required super.productId,
      required super.sales,
      required super.orderDate});

  factory OrderDataModel.fromJson(Map<String, dynamic> json) {
    return OrderDataModel(
      orderId: json['Order ID'],
      profit: double.parse(json['Profit']),
      city: json['City'],
      customerName: json['Customer Name'],
      productName: json['Product Name'],
      rowId: json['Row ID'],
      country: json['Country'],
      discount: double.parse(json['Discount']),
      customerId: json['Customer ID'],
      region: json['Region'],
      quantity: int.parse(json['Quantity']),
      segment: json['Segment'],
      state: json['State'],
      shipMode: json['Ship Mode'],
      subCategory: json['Sub-Category'],
      postalCode: json['Postal Code'],
      shipDate: json['Ship Date'],
      category: json['Category'],
      productId: json['Product ID'],
      sales: double.parse(json['Sales']),
      orderDate: json['Order Date'],
    );
  }

  // Map<String, dynamic> toJson() {
  //   return {
  //     'Order ID': orderId,
  //     'Profit': profit.toString(),
  //     'City': city,
  //     'Customer Name': customerName,
  //     'Product Name': productName,
  //     'Row ID': rowId,
  //     'Country': country,
  //     'Discount': discount.toString(),
  //     'Customer ID': customerId,
  //     'Region': region,
  //     'Quantity': quantity.toString(),
  //     'Segment': segment,
  //     'State': state,
  //     'Ship Mode': shipMode,
  //     'Sub-Category': subCategory,
  //     'Postal Code': postalCode,
  //     'Ship Date': shipDate,
  //     'Category': category,
  //     'Product ID': productId,
  //     'Sales': sales.toString(),
  //     'Order Date': orderDate,
  //   };
  // }

  // Order copyWith({
  //   String? orderId,
  //   double? profit,
  //   String? city,
  //   String? customerName,
  //   String? productName,
  //   String? rowId,
  //   String? country,
  //   double? discount,
  //   String? customerId,
  //   String? region,
  //   int? quantity,
  //   String? segment,
  //   String? state,
  //   String? shipMode,
  //   String? subCategory,
  //   String? postalCode,
  //   String? shipDate,
  //   String? category,
  //   String? productId,
  //   double? sales,
  //   String? orderDate,
  // }) {
  //   return Order(
  //     orderId: orderId ?? this.orderId,
  //     profit: profit ?? this.profit,
  //     city: city ?? this.city,
  //     customerName: customerName ?? this.customerName,
  //     productName: productName ?? this.productName,
  //     rowId: rowId ?? this.rowId,
  //     country: country ?? this.country,
  //     discount: discount ?? this.discount,
  //     customerId: customerId ?? this.customerId,
  //     region: region ?? this.region,
  //     quantity: quantity ?? this.quantity,
  //     segment: segment ?? this.segment,
  //     state: state ?? this.state,
  //     shipMode: shipMode ?? this.shipMode,
  //     subCategory: subCategory ?? this.subCategory,
  //     postalCode: postalCode ?? this.postalCode,
  //     shipDate: shipDate ?? this.shipDate,
  //     category: category ?? this.category,
  //     productId: productId ?? this.productId,
  //     sales: sales ?? this.sales,
  //     orderDate: orderDate ?? this.orderDate,
  //   );
  // }
}
